### ISSUE TITLE
build issues on Ubuntu 14.04 and workarounds

### ISSUE THREAD

**Issue by DennisOSRM** [facebook/flint#20]
If boost is installed thru meta-package `libboost-all-dev` (as opposed to the *`-1.54` packages ) then `./configure` won't pick it up. The following line is a workaround by explicitly specifying the build dir:

```bash
./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu
```

Any plans to use a (excuse me) proper build system like CMake? :grinning:

**Comment by tomdz** [comment]
I've updated to the most recent autoconf definition files for boost which should fix this.
