### ISSUE TITLE
Folly path hardcoded in cxx/Makefile.am

### ISSUE THREAD

**Issue by jbreitbart** [facebook/flint#22]
II do not have folly installed in its default path. The Makefile.am in the cxx subdirectory has the default path hardcoded, so 

make install

failed on my system. As a work-a-round I just modified the Makefile.am to use my installation.

**Comment by joda70** [comment]
It is enough to add the options --with-folly-include and --with-folly-lib in the file folly.m4.
I can provide the file if you do not have time.

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jbreitbart** [comment]
As far as I understand it, folly is no longer required. So I'll just close it myself.
